# Generated by Django 2.0.5 on 2018-05-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180517_1719'),
        ('blog', '0002_auto_20180511_2041'),
    ]

    operations = [
    ]
